name: Build documentation

on:
  pull_request:
    branches: [main]
  workflow_call:
  workflow_dispatch:


jobs:

  build:
    runs-on: ubuntu-22.04
    container: ghcr.io/fenics/dolfinx/lab:stable
    env:
      PUBLISH_DIR: ./_build/html

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: python3 -m pip install ".[docs]"

      - name: Build docs
        run: jupyter-book build -W --keep-going .

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.PUBLISH_DIR }}
