name: CI

on:
  pull_request:
  push:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/fenics/dolfinx/dolfinx:stable

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python3 -m pip install -e ".[test]"

      - name: Test with pytest
        run: |
          python3 -m pytest
